os: linux
dist: bionic
language: python
python: "3.7"

script:
  # Installs & configurations
  - git config --global user.email "bincrafters@gmail.com"
  - git config --global user.name "bincrafters-user"
  - pip install --quiet bincrafters-conventions
  - conan user  # initialize Conan registry file

  # Run bincrafters-conventions to update repositories on pushes & cron
  - if [ ! "${TRAVIS_EVENT_TYPE}" == "api" ]; then
      bincrafters-conventions --remote-add-gha-secrets bincrafters --remote-token="${GITHUB_USERNAME}:${GITHUB_TOKEN}";
      bincrafters-conventions --remote bincrafters --remote-max-repos ${CRON_REMOTE_MAX_REPOS} --remote-token="${GITHUB_USERNAME}:${GITHUB_TOKEN}";
    fi
