matrix:
  fast_finish: true
  include:
  - os: linux
    sudo: false
    language: python
    python: '2.7'
  - os: linux
    sudo: false
    language: python
    python: '3.6'
  - os: osx
    language: generic
    osx_image: xcode9
install:
- ".travis/install.sh"
script:
- ".travis/run.sh"
after_success:
- codecov
deploy:
  provider: pypi
  user: uilianries
  password:
    secure: d77dr62otiPfVP5ZIrUZjvxQK8C77hXDXKOQ1docKmNhjC3RDN9VUGiW7j5gbKxd4RYT5NBWahhhPh0plja9p1ZORNIxangeFiOj1THgYROtRR03YOzPWiWu3tIyfyt4pkf1TciioGLEXMBxSYOQyF8S8oQ4QlECrKIsGh1aX+RrB15m50zPqgvIi6q8ecZEuZiOKtwDFwQmyG9fkwAUvGQmmvZ03KR4QghYHUD/O5nHTDPjMJ9tQyPHAy6gP4J13I5Aj/px5T/7ABV0hP6wa0BUpZ9F6y7BVXKLRMKJOUfTOo9KVK3eFmFHR/6Euq8CmGKKormVijZNJBc2dSi8u4RkKO6EXFVzbAV37NiRO2XwcAqAXL015AdlQF5qdUM1RTiaHcxKCw+6q57Xi0yuo5bqX2UaZDiV4/5+VcgnUEhkDvU/LqxdFurxecqM1WKIYYHLqy6+x+bNzLUug01horJ9l9kOpkwHu+KzBTAiedoGPDFi+PZxA+wYPkhFBGRAeFVpQAwmT245hhIoxxq8CXmjF3PxVTUkHsDcOTF0kHCAgXThk9LOOdKT5D3ugT+5BW60uUmt9utQlLgWdgGRM9UqYdao3i/zr+cwVRpIstBiqy1zBsLJv/y42VGzJ8RWYVdxHhGf/V3S4utQmRTuQh5K5uJL7Uwl1nXvChOjnCg=
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = '2.7'
