matrix:
  include:
  - os: linux
    dist: bionic
    language: python
    python: '3.7'

install:
  - chmod +x .ci/install.sh
  - ".ci/install.sh"

script:
  - chmod +x .ci/run.sh
  - ".ci/run.sh"

after_success:
  - codecov

deploy:
  - provider: pypi
    user: ${PYPI_USERNAME}
    password: ${PYPI_PASSWORD}
    on:
      tags: true
    skip_cleanup: true
    skip_existing: true
  - provider: pypi
    user: ${TEST_PYPI_USERNAME}
    server: https://test.pypi.org/legacy/
    password: ${TEST_PYPI_PASSWORD}
    on:
      branch: main
    skip_cleanup: true
    skip_existing: true
