os: linux
dist: xenial
language: python
python: "3.7"

script:
  - pip install bincrafters-conventions 
  - git config --global user.email "bincrafters@gmail.com"
  - git config --global user.name "bincrafters-user"
  - bincrafters-conventions --remote bincrafters --remote-max-repos ${CRON_REMOTE_MAX_REPOS} --remote-token="${GITHUB_USERNAME}:${GITHUB_TOKEN}"
