build: false


environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install -e .[test]

test_script:
- cd tests
- pytest -v --cov=bincrafters_conventions
