# We need to split the cron jobs, 
# as a single cron job is only allowed to cause 100 runs per week
# We need 7*24=168 runs per week

schedules:
  - cron: '0 * * * 1-4'
    displayName: "Hourly build Monday-Thursday"
    branches:
      include: ['cron']
  - cron: '0 * * * 0,5,6'
    displayName: "Hourly build Friday-Sunday"
    branches:
      include: ['cron']

jobs:
  - job: Linux
    pool:
      vmImage: "ubuntu-18.04"
    steps:
    - script: |
        chmod +x ./trigger-travis.sh
        source ./trigger-travis.sh
      env:
        TRAVIS_TOKEN: $(TRAVIS_TOKEN)
