# We should not need to split the cron jobs, 
# as a single cron job is allowed to cause 1000 runs per week
# We need 7*24=168 runs per week


schedules:
  - cron: "0 * * * *"
    displayName: "Hourly build Monday-Thursday"
    branches:
      include: ["cron"]
    always: true

jobs:
  - job: Linux
    displayName: "Updates from upstream"
    pool:
      vmImage: "ubuntu-18.04"
    steps:
    - script: |
        chmod +x ./cci/update_from_upstream.sh
        source ./cci/update_from_upstream.sh
      env:
        TRAVIS_TOKEN: $(TRAVIS_TOKEN)
        GIT_GITHUB_TOKEN: $(GITHUB_TOKEN)
        GIT_GITHUB_USERNAME: $(GITHUB_USERNAME)
