on: [push, pull_request]

name: "conventions"

jobs:
  bincrafters-conventions-test-v2:
    name: Test with Conan v2 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "windows-2022", "macos-11.0"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: "Build"
      shell: bash
      run: |
        pip install conan=="2.*"
        pip install -e .[test]
        python setup.py sdist
    - name: "Test"
      shell: bash
      run: |
        cd tests
        pytest -v -s --cov=bincrafters_conventions
        mv .coverage ..
        cd ..
        codecov
  bincrafters-conventions-test-v1:
    name: Test with Conan v1 on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "windows-2019", "macos-11.0"]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      # This should be considered the minimum Python version supported
      # Don't just update this without reason
      with:
        python-version: "3.8"
    - name: "Build"
      shell: bash
      run: |
        pip install conan=="1.*"
        pip install -e .[test]
        python setup.py sdist
    - name: "Test"
      shell: bash
      run: |
        cd tests
        pytest -v -s --cov=bincrafters_conventions
        mv .coverage ..
        cd ..
        codecov
  bincrafers-conventions-deploy:
    name: Deploy Conventions to PyPi
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [bincrafters-conventions-test-v1, bincrafters-conventions-test-v2]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Build
      run: |
        python setup.py sdist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
