on:
  push:
  pull_request:
    # only run on pull_request trigger when they come from a fork
    types: [opened, synchronize]
    branches-ignore:
      - '**'

name: "conventions"

jobs:
  bincrafters-conventions-test:
    name: Test with Conan v${{ matrix.conan_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "windows-2019", "macos-11.0"]
        python_version:
          - "3.8"
          - "3.12"
        conan_version:
          - "1"
          - "2"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: "Build"
      shell: bash
      run: |
        pip install conan=="${{ matrix.conan_version }}.*"
        pip install -e .[test]
        python -m pip install build
        python -m build
    - name: "Test"
      shell: bash
      run: |
        cd tests
        pytest -v -s --cov=bincrafters_conventions
        mv .coverage ..
        cd ..
        codecov
  bincrafers-conventions-deploy:
    name: Deploy Conventions to PyPi
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [bincrafters-conventions-test,]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Build
      run: |
        python -m pip install build
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
