on:
  push:
  schedule:
    - cron: "0 0 * * *"

name: "remove-outdated-packages"

jobs:
  remove-outdated-packages:
    name: "Remove Outdated Packages For Bincrafters"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: "Install Conan"
      run: |
        pip install conan
    - name: "Remove Outdated Packages"
      env:
        CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
        CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
        CONAN_REQUEST_TIMEOUT: 3600
        CONAN_LOGGING_LEVEL: 10
      run: |
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        conan user ${CONAN_LOGIN_USERNAME} -r bincrafters -p ${CONAN_PASSWORD}
        conan remove -r bincrafters --outdated --force "*/*"
